### PR TITLE
Complete Admin dashboard project

### PR DESCRIPTION
**Pull request by Phildeoner**
- Created an admin dashboard
- Implemented the usage of CSS Grids and Flexbox
- Added transitions and animations

### CODE REVIEW

**Comment by antoHero** [comment]
Hello @Phildeoner , great job on the dashboard. These are my observations
- I love the animations you added 👍👍
- the search icon should be in your input field in the top navigation
- it is standard practice to have only the search bar, notification icons, profile dropdown cards on the navigation. As result, I'll advice you to move the component with 'Hi there, ... and those buttons from the top navigation to the page itself. Add the card with those contents just before 'Your projects' this will ensure that you do not have the component in your other pages as well
- what do you think about making the background color of the 'New, Upload, and share' buttons darker and still maintaining the white font color?
- the dashboard isn't responsive but I believe you intend working on that
- you can look at other dashboards for inspiration as it will be cool to add tables and graphs (not necessary at this point)

Good job so far 😎

**Review by DanSam5K — APPROVED** [review]

**Review by DanSam5K — COMMENTED** [review]
- In addition to what the previous reviewer suggested
- You may consider improving the documentation also.

**Review by DanSam5K — COMMENTED** [review]
-

**Review by DanSam5K — APPROVED** [review]
# Hi @Phildeoner, ✌️ 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by antoHero** [comment]
# Good job @Phildeoner,
You are in the clear to merge your changes. Great work 👏

**Comment by Phildeoner** [comment]
Thank you Sirs for your reviews.

**Pull request merged**
